version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongo:27017/m365_connector?authSource=admin
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - m365-network
    tty: true
    stdin_open: true

  mongo:
    image: mongo:7.0
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - m365-network

volumes:
  mongo_data:

networks:
  m365-network:
    driver: bridge