version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongo:27017/inbox_connector_db?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/.venv
      - ./docker_keyring:/root/.local/share/python_keyring
    networks:
      - m365-network
    tty: true
    stdin_open: true
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    hostname: mongo
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - m365-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  m365-network:
    driver: bridge